apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  opendatahub.io/component: "true"
  component.opendatahub.io/name: odhargo

generatorOptions:
  disableNameSuffixHash: true

namespace: opendatahub

resources:
  - namespace-install.yaml
  - argo-server-route.yaml
  - default-sa-argo-additions-role.yaml
  - default-sa-rolebinding.yaml
  - workflow-controller-metrics-route.yaml

patchesStrategicMerge:
  - workflow-controller-configmap.yaml
