kind: ConfigMap
apiVersion: v1
metadata:
  name: dex
data:
  config.yaml: |
    issuer: http://dex-aiops-prod-argo.apps.tcoufaltest.lab.pnq2.cee.redhat.com/api/dex

    storage:
      type: memory

    web:
      http: "0.0.0.0:5556"

    grpc:
      addr: "0.0.0.0:5557"

    telemetry:
      http: "0.0.0.0:5558"

    oauth2:
      skipApprovalScreen: true

    staticClients:
      - id: argo
        name: Argo
        secret: ZXhhbXBsZS1hcHAtc2VjcmV0
        redirectURIs:
          - http://argo-server-aiops-prod-argo.apps.tcoufaltest.lab.pnq2.cee.redhat.com/oauth2/callback

      - id: argo-cli
        name: Argo CLI
        public: true
        redirectURIs:
          - http://localhost


    connectors:
      - type: openshift
        id: openshift
        name: OpenShift
        config:
          issuer: https://kubernetes.default.svc
          clientID: system:serviceaccount:aiops-prod-argo:dex
          clientSecret: $DEX_OAUTH_CLIENT_SECRET
          insecureCA: true
          redirectURI: http://dex-aiops-prod-argo.apps.tcoufaltest.lab.pnq2.cee.redhat.com/api/dex/callback
          groups:
            - testgroup
            # - data-hub-openshift-admins
            # - aicoe-thoth-devops
            # - aicoe-aiops-devops
            # - aicoe-argocd-admins
            # - aicoe-ccx
