apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: aiops-prod-argo

commonLabels:
  app.kubernetes.io/name: argo
  app.kubernetes.io/component: workflow-engine
  app.kubernetes.io/part-of: aiops-analytics
  app.kubernetes.io/managed-by: aicoe-aiops-devops-argocd

resources:
  - ../../base
  - ./membership.yaml
  # - ./argo-sso-token.yaml
  # - ./argo-sso-sa.yaml

# components:
#   - ../../components/dex

# configMapGenerator:
#   - name: argocd-cm
#     files:
#       - argocd-cm/dex.config
#       - argocd-cm/url

patchesStrategicMerge:
  - ./workflow-controller-configmap.yaml
patchesJson6902:
  - patch: |
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --auth-mode
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: sso

    #       - op: add
    #         path: /spec/template/spec/containers/0/volumeMounts
    #         value:
    #           - mountPath: "/etc/ssl/certs/"
    #             name: ssl
    #             readOnly: True
    #       - op: add
    #         path: /spec/template/spec/volumes
    #         value:
    #           - name: ssl
    #             secret:
    #               secretName: argo-sso-token
    target:
      group: apps
      kind: Deployment
      name: argo-server
      version: v1
