apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
data:
  workflowDefaults: |
    spec:
      # must complete in 8h (28,800 seconds)
      activeDeadlineSeconds: 28800

      # keep workflows for 24h (86,400 seconds). If workflow succeeded keep for 1h (3,600 seconds) only
      ttlStrategy:
        secondsAfterCompletion: 86400
        secondsAfterSuccess: 3600
  sso: |
    issuer: http://dex-aiops-prod-argo.apps.tcoufaltest.lab.pnq2.cee.redhat.com/api/dex
    clientId:
      name: dex-client
      key: client
    clientSecret:
      name: dex-client
      key: token
    redirectUrl: http://argo-server-aiops-prod-argo.apps.tcoufaltest.lab.pnq2.cee.redhat.com/oauth2/callback
    rbac:
      enabled: false
